### PR TITLE
2.0.0: now including node-sass in the build

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by arjansingh** [comment]
I would accept this PR.

The docker container is not starting properly: https://travis-ci.org/dollarshaveclub/fastboot-docker/builds/186822935#L6102-L6108

Please fix.

**Comment by briangonzalez** [comment]
@arjansingh Looks like a change you made a few months back is causing the image not to run: `NODE_ENV` used before declaration

https://github.com/dollarshaveclub/fastboot-docker/blob/master/test/fixtures/fastboot-app/server/middleware/after-fastboot.js#L3

I've pushed a fix.

**Comment by briangonzalez** [comment]
@arjansingh That was it.

**Comment by arjansingh** [comment]
Rebase and we'll accept.

**Comment by arjansingh** [comment]
Image size will go from 16MB to 57MB

**Comment by arjansingh** [comment]
Also please update/delete [Notes](https://github.com/dollarshaveclub/fastboot-docker#notes)

**Comment by briangonzalez** [comment]
@arjansingh Done.

**Review by arjansingh — APPROVED** [review]

**Comment by arjansingh** [comment]
@briangonzalez please build and publish images to `:latest` `2` and `2.0.0`.

**Comment by briangonzalez** [comment]
Done.

**Comment by briangonzalez** [comment]
https://hub.docker.com/r/dollarshaveclub/fastboot/tags/

**Pull request merged**
